[[model]]
    name = "r100"
    path = "/Users/load/code/python/infinivision/tvm-convert/tvm-model"
    input_shape = [[112,112]]

[http]
    ip   = 127.0.0.1 
    port = 80

[server]
    cpu = "skylake"
    omp_num_thread = 4